#!/bin/sh

cd `dirname $0`/../

# format code
clang-format -style="{BasedOnStyle: llvm, IndentWidth: 4, AllowShortFunctionsOnASingleLine: None, SortIncludes: false, KeepEmptyLinesAtTheStartOfBlocks: false, ColumnLimit: 120}" -i \
    `find ./ -type f -name "*.cpp" -o \
                     -type f -name "*.c" -o \
                     -type f -name "*.h" -o \
                     -type f -name "*.hpp"`


# Format CMake
cmake-format -i CMakeLists.txt cmake/*
