var annotated_dup =
[
    [ "wows_assets_bin_bb_list_t", "structwows__assets__bin__bb__list__t.html", "structwows__assets__bin__bb__list__t" ],
    [ "wows_assets_bin_bb_t", "structwows__assets__bin__bb__t.html", "structwows__assets__bin__bb__t" ],
    [ "wows_assets_bin_hp_list_t", "structwows__assets__bin__hp__list__t.html", "structwows__assets__bin__hp__list__t" ],
    [ "wows_assets_bin_hp_t", "structwows__assets__bin__hp__t.html", "structwows__assets__bin__hp__t" ],
    [ "wows_assets_bin_lod_t", "structwows__assets__bin__lod__t.html", "structwows__assets__bin__lod__t" ],
    [ "wows_assets_bin_propeller_list_t", "structwows__assets__bin__propeller__list__t.html", "structwows__assets__bin__propeller__list__t" ],
    [ "wows_assets_bin_propeller_t", "structwows__assets__bin__propeller__t.html", "structwows__assets__bin__propeller__t" ],
    [ "wows_assets_bin_rs_t", "structwows__assets__bin__rs__t.html", "structwows__assets__bin__rs__t" ],
    [ "wows_assets_bin_visual_info_t", "structwows__assets__bin__visual__info__t.html", "structwows__assets__bin__visual__info__t" ],
    [ "wows_geometry", "structwows__geometry.html", "structwows__geometry" ],
    [ "WOWS_GEOMETRY_CONTEXT", "struct_w_o_w_s___g_e_o_m_e_t_r_y___c_o_n_t_e_x_t.html", "struct_w_o_w_s___g_e_o_m_e_t_r_y___c_o_n_t_e_x_t" ],
    [ "wows_geometry_header", "structwows__geometry__header.html", "structwows__geometry__header" ],
    [ "wows_geometry_index_section", "structwows__geometry__index__section.html", "structwows__geometry__index__section" ],
    [ "wows_geometry_index_section_metadata", "structwows__geometry__index__section__metadata.html", "structwows__geometry__index__section__metadata" ],
    [ "wows_geometry_info", "structwows__geometry__info.html", "structwows__geometry__info" ],
    [ "wows_geometry_vertex_section", "structwows__geometry__vertex__section.html", "structwows__geometry__vertex__section" ],
    [ "wows_geometry_vertex_section_metadata", "structwows__geometry__vertex__section__metadata.html", "structwows__geometry__vertex__section__metadata" ],
    [ "wows_glb_part", "structwows__glb__part.html", "structwows__glb__part" ],
    [ "wows_hull_info", "structwows__hull__info.html", "structwows__hull__info" ],
    [ "wows_mount_entry", "structwows__mount__entry.html", "structwows__mount__entry" ],
    [ "wows_ship_entry", "structwows__ship__entry.html", "structwows__ship__entry" ],
    [ "wows_ship_export_options", "structwows__ship__export__options.html", "structwows__ship__export__options" ],
    [ "wows_vert_xyznuvrpc", "structwows__vert__xyznuvrpc.html", "structwows__vert__xyznuvrpc" ],
    [ "wows_vert_xyznuvtbpc", "structwows__vert__xyznuvtbpc.html", "structwows__vert__xyznuvtbpc" ],
    [ "wows_vertex", "structwows__vertex.html", null ]
];