int vertex2id(const char *vertex_type);
const char *id2vertex(int id);
uint8_t geom_datatoh8(char *data, size_t offset, WOWS_GEOMETRY_CONTEXT *context);
uint16_t geom_datatoh16(char *data, size_t offset, WOWS_GEOMETRY_CONTEXT *context);
uint32_t geom_datatoh32(char *data, size_t offset, WOWS_GEOMETRY_CONTEXT *context);
uint64_t geom_datatoh64(char *data, size_t offset, WOWS_GEOMETRY_CONTEXT *context);
void normalise(float *x, float *y, float *z);
float clamp(float min, float value, float max);
int wows_unpack_normal_old(wows_vertex *vertex_packed);
int wows_pack_normal_old(wows_vertex *vertex_packed);
float f16_to_f32(uint16_t h);
void wows_unpack_normal(uint32_t packed, float *nx, float *ny, float *nz);
void wows_unpack_uv(uint32_t packed, float *u, float *v);
