name: Coverage

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install packages
      run: |
        sudo apt update
        sudo apt install cmake zlib1g-dev libpcre2-dev clang lcov libcunit1-dev \
          libmeshoptimizer-dev libtinygltf-dev libstb-dev python3-dev

    - name: Configure CMake
      run: cmake -DCOVERAGE=ON -DBUILD_TESTS=ON .

    - name: Build
      run: make

    - name: Test
      run: make coverage

    - name: Generate Coverage Report
      run: lcov --directory . --capture --output-file coverage.info

    - name: Upload Coverage Report
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage.info
